platform :ios, '10'

install! 'cocoapods', :disable_input_output_paths => true

target 'Modern Collection Views' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'ConfigableCollectionView', :path => '..'
end