platform :ios, '10'

install! 'cocoapods', :disable_input_output_paths => true
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'ConfigableCollectionViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'ConfigableCollectionView', :path => '../Source'
end